/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author andre
 */
public class Dijkstra extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dijkstra.class.getName());
    
    // CONEXIÓN CON TU LÓGICA: Variables globales para almacenar los datos que vienen de VentanaPrincipal
    private Estructuras.Grafo grafo;
    private Estructuras.HashTable tablaNT;

    /**
     * CONSTRUCTOR CORREGIDO: Ahora recibe los datos reales del sistema
     */
    public Dijkstra(Estructuras.Grafo grafo, Estructuras.HashTable tablaNT) {
        initComponents();
        this.grafo = grafo;
        this.tablaNT = tablaNT;
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Evita que se cierre todo el programa al cerrar esta ventana
        cargarComboNeuronas(); // Llena los JComboBox automáticamente con los IDs reales
    }
    
    /**
     * Constructor por defecto (Se mantiene para compatibilidad con el diseñador de NetBeans)
     */
    public Dijkstra() {
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * MÉTODO AUXILIAR: Llena ambos ComboBoxes dinámicamente con los IDs de tus neuronas reales
     */
    private void cargarComboNeuronas() {
        if (this.grafo == null) return;
        
        // Limpiamos los elementos de prueba que pone NetBeans
        cbDijkstraOrigen.removeAllItems();
        cbDijkstraDestino.removeAllItems();
        
        // Obtenemos la lista de neuronas de tu clase Grafo
        Estructuras.ListaPropia<Modelo.Neurona> lista = grafo.getNeuronas();
        for (int i = 0; i < lista.getTamaño(); i++) {
            String id = lista.obtener(i).getId();
            cbDijkstraOrigen.addItem(id);
            cbDijkstraDestino.addItem(id);
        }
    }

    /**
     * MÉTODO AUXILIAR: Ejecuta la lógica de Dijkstra al presionar el botón
     */
/**
     * MÉTODO AUXILIAR: Ejecuta la lógica de Dijkstra al presionar el botón
     */
    private void ejecutarDijkstra() {
        if (this.grafo == null || cbDijkstraOrigen.getSelectedItem() == null || cbDijkstraDestino.getSelectedItem() == null) {
            return;
        }
        
        String origen = cbDijkstraOrigen.getSelectedItem().toString();
        String destino = cbDijkstraDestino.getSelectedItem().toString();
        
        // Si eligen la misma neurona, no hace falta calcular nada
        if (origen.equals(destino)) {
            IblResultadoRuta.setText("Ruta: " + origen);
            IblTiempoTotal.setText("Tiempo Total: 0.0 ms");
            return;
        }
        
        // Ejecutamos tu método dijkstra pasándole el origen
        String resultadoCamino = grafo.dijkstra(origen); 
        
        // Mostramos el resultado de los caminos en tu etiqueta de texto
        IblResultadoRuta.setText("Ruta: " + resultadoCamino);
        IblTiempoTotal.setText("Caminos optimizados desde " + origen + " con éxito.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbDijkstraOrigen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbDijkstraDestino = new javax.swing.JComboBox<>();
        btnCalcularDijkstra = new javax.swing.JButton();
        IblResultadoRuta = new javax.swing.JLabel();
        IblTiempoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Neurona Origen");

        cbDijkstraOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "7" }));

        jLabel2.setText("Neurona Destino");

        cbDijkstraDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "7" }));

        btnCalcularDijkstra.setText("Calcular Ruta");

        IblResultadoRuta.setText("Ruta");

        IblTiempoTotal.setText("Tiempo Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbDijkstraOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(IblResultadoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalcularDijkstra)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbDijkstraDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IblTiempoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDijkstraOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(IblResultadoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbDijkstraDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IblTiempoTotal))
                .addGap(36, 36, 36)
                .addComponent(btnCalcularDijkstra)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
     * EVENTO DEL BOTÓN: Ejecuta los cálculos del algoritmo
     */
    private void btnCalcularDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularDijkstraActionPerformed
        ejecutarDijkstra();
    }//GEN-LAST:event_btnCalcularDijkstraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Comentado para evitar ejecuciones independientes sin datos */
        // java.awt.EventQueue.invokeLater(() -> new Dijkstra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblResultadoRuta;
    private javax.swing.JLabel IblTiempoTotal;
    private javax.swing.JButton btnCalcularDijkstra;
    private javax.swing.JComboBox<String> cbDijkstraDestino;
    private javax.swing.JComboBox<String> cbDijkstraOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
