/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Modelo.Neurona;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author andre
 */
public class MostrarGrafo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MostrarGrafo.class.getName());
    
    // Conexión con tu estructura de datos
    private Estructuras.Grafo grafo;
    private double factorZoom = 1.0;

    /**
     * Constructor corregido que recibe el Grafo del sistema
     */
    public MostrarGrafo(Estructuras.Grafo grafo) {
        initComponents();
        this.grafo = grafo;
        this.setLocationRelativeTo(null); // Centrar la ventana
        
        // Evitar que cierre toda la aplicación al cerrar solo esta pantalla
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Listener para cambiar el zoom mediante el ComboBox
        cbZoom.addActionListener(e -> {
            String seleccion = (String) cbZoom.getSelectedItem();
            if (seleccion != null) {
                if (seleccion.equals("50%")) factorZoom = 0.5;
                else if (seleccion.equals("100%")) factorZoom = 1.0;
                else if (seleccion.equals("150%")) factorZoom = 1.5;
                PanelGrafo.repaint();
            }
        });
        
        // Agregar acción al botón Zoom Menos que faltaba enlazar
        btnZoomMenos.addActionListener(e -> {
            if (factorZoom > 0.5) {
                factorZoom -= 0.25;
                PanelGrafo.repaint();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbZoom = new javax.swing.JComboBox<>();
        btnZoomMas = new javax.swing.JButton();
        btnZoomMenos = new javax.swing.JButton();
        chbMostrarPesos = new javax.swing.JCheckBox();
        chbMostrarEtiquetas = new javax.swing.JCheckBox();
        PanelGrafo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        IblNeuronaNormal = new javax.swing.JLabel();
        IblNeuronaAlcanzable = new javax.swing.JLabel();
        IblNeuronaAislada = new javax.swing.JLabel();
        IblNeuronaNoExplorada = new javax.swing.JLabel();
        IblSinapsisLeyenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Zoom");

        cbZoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50%", "100%", "150%" }));

        btnZoomMas.setText("+");
        btnZoomMas.addActionListener(this::btnZoomMasActionPerformed);

        btnZoomMenos.setText("-");

        chbMostrarPesos.setText("Mostrar Pesos");

        chbMostrarEtiquetas.setText("Mostrar Etiquetas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnZoomMenos, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnZoomMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbMostrarPesos)
                    .addComponent(chbMostrarEtiquetas))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnZoomMas, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbMostrarPesos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnZoomMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbMostrarEtiquetas, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );

        PanelGrafo.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Leyenda"));

        IblNeuronaNormal.setForeground(new java.awt.Color(51, 153, 255));
        IblNeuronaNormal.setText("Neurona Normal");

        IblNeuronaAlcanzable.setForeground(new java.awt.Color(51, 255, 51));
        IblNeuronaAlcanzable.setText("Neurona Alcanzable");

        IblNeuronaAislada.setForeground(new java.awt.Color(255, 0, 0));
        IblNeuronaAislada.setText("Neurona Aislada");

        IblNeuronaNoExplorada.setForeground(new java.awt.Color(153, 153, 153));
        IblNeuronaNoExplorada.setText("Neurona No Explorada");

        IblSinapsisLeyenda.setText("Sinapsis");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IblNeuronaNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IblNeuronaAlcanzable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IblNeuronaAislada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(IblNeuronaNoExplorada)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(IblSinapsisLeyenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IblNeuronaNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IblNeuronaAlcanzable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IblNeuronaAislada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IblNeuronaNoExplorada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IblSinapsisLeyenda)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelGrafoLayout = new javax.swing.GroupLayout(PanelGrafo);
        PanelGrafo.setLayout(PanelGrafoLayout);
        PanelGrafoLayout.setHorizontalGroup(
            PanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGrafoLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelGrafoLayout.setVerticalGroup(
            PanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGrafoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(PanelGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZoomMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomMasActionPerformed
if (factorZoom < 2.0) {
            factorZoom += 0.25;
            PanelGrafo.repaint();
        }    }//GEN-LAST:event_btnZoomMasActionPerformed

    /**
     * Método lógico para pintar el grafo en tiempo real
     */
    private void dibujarRedNeuronal(Graphics g) {
        if (this.grafo == null) return;

        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        Estructuras.ListaPropia<Neurona> lista = grafo.getNeuronas();
        int total = lista.getTamaño();
        if (total == 0) return;

        int centroX = PanelGrafo.getWidth() / 2;
        int centroY = PanelGrafo.getHeight() / 2;
        int radioVisual = (int) (Math.min(centroX, centroY) * 0.6 * factorZoom);

        int[] posX = new int[total];
        int[] posY = new int[total];
        int diametroNodo = (int) (30 * factorZoom);

        for (int i = 0; i < total; i++) {
            double angulo = 2 * Math.PI * i / total;
            posX[i] = centroX + (int) (radioVisual * Math.cos(angulo));
            posY[i] = centroY + (int) (radioVisual * Math.sin(angulo));
        }

        // 1º PASO: Dibujar las Sinapsis (Líneas de conexión) utilizando tu lógica real de clases
        g2.setColor(Color.BLACK);
        for (int i = 0; i < total; i++) {
            Neurona origen = lista.obtener(i);
            if (origen == null) continue;

            // Extraemos las sinapsis de la neurona origen directamente
            Estructuras.ListaPropia<Modelo.Sinapsis> conexiones = origen.getConexiones();
            
            for (int j = 0; j < total; j++) {
                if (i == j) continue;
                Neurona destino = lista.obtener(j);
                if (destino == null) continue;

                // Buscamos si existe una sinapsis que apunte a la neurona destino
                for (int k = 0; k < conexiones.getTamaño(); k++) {
                    Modelo.Sinapsis s = conexiones.obtener(k);
                    
                    if (s.getDestino().getId().equals(destino.getId())) {
                        // ¡Se encontró la sinapsis! Dibujamos la línea
                        g2.drawLine(posX[i], posY[i], posX[j], posY[j]);

                        if (chbMostrarPesos.isSelected()) {
                            // Calculamos el peso tal cual lo tienes en tu método Dijkstra: distancia / (velocidad * k)
                            // Como no tenemos acceso directo a tablaNT aquí, mostramos el atributo de 'distancia' o 'k' como peso visual alternativo
                            double pesoVisual = s.getDistancia(); 
                            
                            int medX = (posX[i] + posX[j]) / 2;
                            int medY = (posY[i] + posY[j]) / 2;
                            g2.setColor(Color.RED);
                            g2.drawString(String.format("%.1f", pesoVisual), medX, medY);
                            g2.setColor(Color.BLACK);
                        }
                        break; // Ya encontramos la conexión, pasamos al siguiente destino
                    }
                }
            }
        }

        // 2º PASO: Dibujar las Neuronas (Círculos)
        for (int i = 0; i < total; i++) {
            Neurona n = lista.obtener(i);
            if (n == null) continue;

            g2.setColor(new Color(51, 153, 255)); // Azul Neurona Normal
            g2.fillOval(posX[i] - diametroNodo / 2, posY[i] - diametroNodo / 2, diametroNodo, diametroNodo);
            g2.setColor(Color.DARK_GRAY);
            g2.drawOval(posX[i] - diametroNodo / 2, posY[i] - diametroNodo / 2, diametroNodo, diametroNodo);

            if (chbMostrarEtiquetas.isSelected()) {
                g2.setColor(Color.BLACK);
                g2.drawString(n.getId(), posX[i] - 10, posY[i] - (diametroNodo / 2) - 4);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblNeuronaAislada;
    private javax.swing.JLabel IblNeuronaAlcanzable;
    private javax.swing.JLabel IblNeuronaNoExplorada;
    private javax.swing.JLabel IblNeuronaNormal;
    private javax.swing.JLabel IblSinapsisLeyenda;
    private javax.swing.JPanel PanelGrafo;
    private javax.swing.JButton btnZoomMas;
    private javax.swing.JButton btnZoomMenos;
    private javax.swing.JComboBox<String> cbZoom;
    private javax.swing.JCheckBox chbMostrarEtiquetas;
    private javax.swing.JCheckBox chbMostrarPesos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
