/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

public class SimularFatiga extends javax.swing.JFrame {

    private Estructuras.Grafo grafo;

    // Constructor correcto que recibe el grafo
    public SimularFatiga(Estructuras.Grafo grafo) {
        initComponents();
        this.grafo = grafo;
        this.setLocationRelativeTo(null); // Centra la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNuevoFactor = new javax.swing.JTextField();
        btnAplicarFatiga = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Esta accion multiplicara todos\n los valores del coeficiente k\n por 1 2 en todas las sinapsis");
        jLabel1.getAccessibleContext().setAccessibleParent(this);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion"));

        jScrollPane1.setToolTipText("Esta accion multiplicara todos  los valores del coeficiente k  por 1 2 en todas las sinapsis");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Esta accion multiplicara todos  los valores del coeficiente k  por 1 2 en todas las sinapsis");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Accion"));

        jLabel3.setText("Factor de Multiplicacion");

        txtNuevoFactor.setText("1.2");

        btnAplicarFatiga.setBackground(new java.awt.Color(0, 153, 255));
        btnAplicarFatiga.setText("Aplicar Fatiga");
        btnAplicarFatiga.addActionListener(this::btnAplicarFatigaActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNuevoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnAplicarFatiga)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNuevoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnAplicarFatiga)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarFatigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarFatigaActionPerformed
try {
            // 1. Convertimos el texto ingresado a un número decimal
            double factor = Double.parseDouble(txtNuevoFactor.getText());
            
            if (factor <= 0) {
                JOptionPane.showMessageDialog(this, "Por favor, ingresa un factor mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2. Modificación de pesos y coeficientes mediante reflexión interna del Grafo
            if (this.grafo != null) {
                java.lang.reflect.Method getNeuronasMetodo = grafo.getClass().getMethod("getNeuronas");
                Object listaNeuronas = getNeuronasMetodo.invoke(grafo);
                
                if (listaNeuronas != null) {
                    java.lang.reflect.Method getTamañoMetodo = listaNeuronas.getClass().getMethod("getTamaño");
                    int tamañoNeuronas = (int) getTamañoMetodo.invoke(listaNeuronas);
                    
                    java.lang.reflect.Method obtenerNeuronaMetodo = listaNeuronas.getClass().getMethod("obtener", int.class);
                    
                    for (int i = 0; i < tamañoNeuronas; i++) {
                        Object neurona = obtenerNeuronaMetodo.invoke(listaNeuronas, i);
                        if (neurona != null) {
                            java.lang.reflect.Method getConexionesMetodo = neurona.getClass().getMethod("getConexiones");
                            Object conexiones = getConexionesMetodo.invoke(neurona);
                            
                            if (conexiones != null) {
                                int tamConexiones = (int) getTamañoMetodo.invoke(conexiones);
                                java.lang.reflect.Method obtenerConexionMetodo = conexiones.getClass().getMethod("obtener", int.class);
                                
                                for (int j = 0; j < tamConexiones; j++) {
                                    Object sinapsis = obtenerConexionMetodo.invoke(conexiones, j);
                                    if (sinapsis != null) {
                                        java.lang.reflect.Method getPesoMetodo;
                                        java.lang.reflect.Method setPesoMetodo;
                                        
                                        // Evaluamos si tus entidades usan la nomenclatura matemática 'K' o la genérica 'Peso'
                                        try {
                                            getPesoMetodo = sinapsis.getClass().getMethod("getK");
                                            setPesoMetodo = sinapsis.getClass().getMethod("setK", double.class);
                                        } catch (NoSuchMethodException e) {
                                            getPesoMetodo = sinapsis.getClass().getMethod("getPeso");
                                            setPesoMetodo = sinapsis.getClass().getMethod("setPeso", double.class);
                                        }
                                        
                                        double pesoActual = (double) getPesoMetodo.invoke(sinapsis);
                                        double nuevoPeso = pesoActual * factor;
                                        setPesoMetodo.invoke(sinapsis, nuevoPeso);
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // 3. Mensaje de éxito
            JOptionPane.showMessageDialog(this, "Fatiga simulada con éxito. Coeficientes actualizados en la red.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // 4. Cierra esta ventana automáticamente
            this.dispose(); 
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El factor de fatiga debe ser un número decimal válido (Ej: 1.2).", "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar propiedades en la estructura del Grafo: " + e.getMessage(), "Error Crítico", JOptionPane.ERROR_MESSAGE);
        }
        }//GEN-LAST:event_btnAplicarFatigaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarFatiga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField txtNuevoFactor;
    // End of variables declaration//GEN-END:variables
}
